name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Deploy-on-Nebula:

    runs-on: ubuntu-18.04

    steps:    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Pull code from repo
      uses: appleboy/ssh-action@v0.1.4
      with: 
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/LogBook/
          sudo git checkout -f 
          sudo git pull origin main

    - name: Deploy
      uses: appleboy/ssh-action@v0.1.4
      with: 
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/LogBook/
          sudo composer install
          sudo php artisan migrate
          sudo php artisan cache:clear
          sudo php artisan config:clear
          sudo php artisan config:cache
          
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
